#!/usr/bin/env python3
import collections
import itertools as it
import math
#import numpy as np
 
#  = input()
#  = int(input())
n, m, x  = map(int, input().split())
li  = [list(map(int, input().split())) for _ in range(m)]
#  = [int(input()) for i in range(N)]
#
# c = collections.Counter()


for i in range(2**m):
    s = f'{i:012b}'[m=12]
    print(s)
